support mips64le architecture.
vmware-tanzu/sonobuoy pull request #1209
Opened 2021-01-22 00:27 UTC by houfangdong

**What this PR does / why we need it**:
It has been verified that sonobuoy can be used normally on the mips64le platform, in order to facilitate the use of it on more architecture platforms, so submit.

**Which issue(s) this PR fixes**
- Fixes #
support more cpu architecture

**Special notes for your reviewer**:

**Release note**:
```
release-note
```
Signed-off-by: houfangdong <houfangdong@loongson.com>

2021-01-22 00:35 UTC, wilsonehusin commented
This is very cool -- thank you so much for submitting!

I'm generally supportive of this idea, though I'm unsure on how we can maintain this / "officially release" since I don't have `mips64le` arch machines around.

Some thoughts:
- Even if we _don't officially support this_, I'd like to make it easy for people to build `mips64le` arch, or any arch for that matter. So I'm personally +1 on adding Makefile, but maybe not on the releases.
- If there is enough interest for this to happen from the community (and perhaps some willing to setup maintenance like continuous integration pipelines for the arch) then it gives me more negotiating power to make this part of official release :)

cc: @vladimirvivien would like to hear your thoughts as well

2021-01-22 01:58 UTC, houfangdong commented
@wilsonehusin，@vladimirvivien,
Thank you for your reply, we can donate mips64le machines to the community with enough interest and willingness to maintain continuous mips64le architecture integration pipeline.
What do you guys think.
We are expecting a reply.

2021-01-30 03:08 UTC, houfangdong commented
Hello, I hope to hear your suggestions, thanks.
@wilsonehusin，@vladimirvivien, @johnSchnake， @zubron

2021-01-30 04:40 UTC, wilsonehusin commented
hello @houfangdong!

recently we've been experimenting on building our pipelines using [`ko`](https://github.com/google/ko) where multi-arch builds will be done by default. this means the current Makefile and other pipeline setup about releases will go through a major change, such that there will be less crumbles in our source code while still making it easy for anyone to run Sonobuoy on any arch. we hope to get this out before end of February.

I will keep this PR open for now -- in case that we miss the schedule, I will consider merging this for your convenience in using Sonobuoy. I'm sorry that the schedule isn't working out better than the current situation, but I hope that once the migration to `ko` completes, this project can stop worrying about architectures.

in any case, thank you so much for the submission and if you have other thoughts related to this issue or just Sonobuoy in general, let us know! we're `#sonobuoy` on Kubernetes Slack and feel free to submit issues for any other requests as well.

2021-01-30 06:25 UTC, houfangdong commented
hi，@wilsonehusin,
Thank you for your prompt reply. I agree with your opinion. The code can be incorporated first, and the release version will be processed at the end of February, right? We are serving multiple cloud vendors and hope to participate in the sonobuoy community and solve related problems.
Looking forward to the next exchange.

2021-02-24 15:50 UTC, wilsonehusin commented
Hey @houfangdong -- looks like we might not get `ko` merged in for the next release. However, we started using `distroless` for our base image and I can't find the base image for `mips64le`. Am I missing something?

2021-02-24 15:54 UTC, wilsonehusin requested changes

2021-02-24 15:54 UTC, wilsonehusin commented on .circleci/config.yml
> +            - build/linux/mips64le/*
I don't think we should publish any images that we don't necessarily test / support. I'm okay with adding the `Makefile` entry for folks to build their own image, but I'm not sure if we should publish this.

2021-02-25 00:37 UTC, houfangdong commented
Hey，@wilsonehusin.
Thank you for your continued attention to this PR.
Okay, I see. You can close this pr first, and we will also submit community submissions to other projects such as **distroless**. After these are supported, we can contribute related pr. At the same time, we will also actively participate in community contributions, not just limited to the mips64le architecture.

2021-02-25 02:31 UTC, wilsonehusin commented
@houfangdong that's awesome to hear that you're actively participating in community contributions. I'll leave this one here just so we can have a reference on progress, but hopefully `ko` solves this. see you around!

2021-05-08 23:33 UTC, johnSchnake commented
👋 Hi, I was looking at this and am currently working a lot on the Windows build support and CI code so I thought I would try and touch base.

First, I think on further investigation we are not sure that the `ko` PR mentioned above will merge.
Second, our CI will soon be using buildx to help us build Windows images and so I'm assuming that would also make supporting mips64le pretty trivial?

I was just curious though, I dont know much about the mips64le architecture and confirmed that, just as a comparison, the google pause image (which k8s testing uses a lot) doesnt build for mips64le either. What is the use case for mips64le+sonobuoy? Are you wanting to run sonobuoy as a client on that machine or are you trying to run k8s on mips64le?

Thanks for feedback on this, it will help me understand how to prioritize this and the scope of the work.

2021-08-24 23:49 UTC, closed without merging