Add governance document and design folder
vmware-tanzu/sonobuoy pull request #1642
Opened 2022-03-17 17:21 UTC by johnSchnake

Signed-off-by: John Schnake <jschnake@vmware.com>

2022-03-18 15:42 UTC, jonasrosland requested changes
Just 2 minor changes, otherwise this looks good!

2022-03-18 15:42 UTC, jonasrosland commented on GOVERNANCE.md
> +Sonobuoy Plugins: This repository contains Sonobuoy plugins
These should be bullet points for formatting

2022-03-18 15:42 UTC, jonasrosland commented on GOVERNANCE.md
> +Sonobuoy Plugins: This repository contains Sonobuoy plugins
And please link to the repos themselves

2022-03-18 15:42 UTC, jonasrosland commented on design/README.md
> +[governance]: https://github.com/vmware-tanzu/sonobuoy/blob/main/Governance.md
Please make sure the filename is correctly capitalized

2022-03-18 18:36 UTC, johnSchnake commented
Fixed based on feedback. Merging after green tests.

2022-03-18 19:44 UTC, jonasrosland approved these changes

2022-03-22 16:50 UTC, eleanor-millman commented on GOVERNANCE.md
> +Sonobuoy, an open source project, is committed to building an open, inclusive, productive and self-governing open source community focused on building a high quality tool that enables users to safely
Need to delete "that enables users to safely backup and restore, perform disaster recovery, and migrate Kubernetes cluster resources and persistent volume". Instead, maybe say "that enables users to check the conformance of their Kubernetes clusters as well as perform automated cluster validations."

2022-03-22 16:56 UTC, merged